// This file is generated by icon spritesheet generator

export const iconNames = [
  "update",
  "sun",
  "plus",
  "moon",
  "laptop",
  "download",
] as const

export type IconName = typeof iconNames[number]
